config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('mainapp.urls',namespace='mainapp')),
    path("", include('dogs.urls', namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.AdminSite.site_header = 'Моя админка'
admin.AdminSite.index_title = 'Главная страница настройки администрования приложения'

dogs/urls.py
from django.urls import path
from dogs.views import DogsDetailView, DogsListView, DogsUpdateView, DogsCreateView, DogsDeleteView

from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path("",			DogsListView.as_view(), name='list'),
    path("Dogs/<int:pk>/", 	DogsDetailView.as_view(), name='detail'),
    path("Dogs/create/", 	DogsCreateView.as_view(), name='create'),
    path("Dogs/update/<int:pk>/",DogsUpdateView.as_view(), name='update'),
    path("Dogs/delete/<int:pk>/",DogsDeleteView.as_view(), name='delete'),
]

dogs/models.py
from django.db import models
from users.models import User

# Create your models here.
BLANKNULL = {'blank':True, 'null':True}

class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название породы', help_text='Введите породу собаки')
    description = models.TextField(verbose_name='Описание породы', help_text='Введите описание породы', **BLANKNULL)
    photo = models.ImageField(upload_to="breeds/photo", verbose_name='Фото породы', help_text='Загрузите фото породы',
                              **BLANKNULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'

class Dogs(models.Model):
    name = models.CharField(max_length=100, verbose_name='Кличка', help_text='Введите кличку собаки')
    breed = models.ForeignKey(Breed, on_delete=models.SET_NULL, verbose_name='Порода', help_text='Введите породу собаки', related_name='dogs', **BLANKNULL)
    photo = models.ImageField(upload_to="dogs/photo", verbose_name='Фото собаки', help_text='Загрузите фото собаки', **BLANKNULL)
    date_born = models.DateField(verbose_name='Дата рождения', help_text='Укажите дату рождения')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец собаки', help_text='Введите идентификатор владельца собаки', related_name='user',**BLANKNULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'
        ordering = ['breed','name']


class Parent(models.Model):
    dog = models.ForeignKey(Dogs, on_delete=models.SET_NULL, verbose_name='Собака',
                              help_text='Выберете собаку', related_name='parent', **BLANKNULL)
    name = models.CharField(max_length=100, verbose_name='Кличка', help_text='Введите кличку предка собаки')
    breed = models.ForeignKey(Breed, on_delete=models.SET_NULL, verbose_name='Порода',
                              help_text='Введите породу предка собаки', related_name='parent_dogs', **BLANKNULL)
    year = models.PositiveIntegerField(verbose_name='Год рождения', help_text='Укажите год рождения',default=100)
    class Meta:
        verbose_name = 'Предок собаки'
        verbose_name_plural = 'Предки собаки'

dogs/forms.py
from datetime import timedelta

from django.core.exceptions import ValidationError
from django.utils import timezone

from django import forms
from django.forms import BooleanField

from dogs.models import Dogs, Breed, Parent

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control text-start'

class DogsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dogs
        exclude = ('owner',)

class ParentForm(forms.ModelForm):
    def clean_year(self):
        year = self.cleaned_data['year']
        current_year = timezone.now().year
        timedelta = current_year - year
        if year > current_year:
            raise ValidationError('Вы ввели год больше текущего.')
        elif timedelta > 100:
            raise ValidationError('Возраст собаки получился более 100 лет. Это ошибка!!!')
        return year

    class Meta:
        model = Parent
        fields = '__all__'

dogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import  CreateView, ListView, DetailView, UpdateView, DeleteView
from dogs.models import Dogs, Breed, Parent
from dogs.forms import DogsForm, ParentForm

# Create your views here.

class DogsDetailView(DetailView):
    model = Dogs

class DogsListView(ListView):
    model = Dogs

class DogsCreateView(CreateView, LoginRequiredMixin):
    model = Dogs
    success_url = reverse_lazy('dogs:list')
    #fields = ("name", 'breed', "photo", "date_born")
    form_class = DogsForm

    def form_valid(self, form):
        dog = form.save()
        user = self.request.user
        dog.owner = user
        dog.save()
        return super().form_valid(form)

class DogsUpdateView(UpdateView):
    model = Dogs
    #fields = ("name", 'breed', "photo", "date_born")
    form_class = DogsForm
    def get_success_url(self):
        return reverse('dogs:detail', args=[self.kwargs.get('pk')] )

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Dogs, Parent, form=ParentForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ParentFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ParentFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

class DogsDeleteView(DeleteView):
    model = Dogs
    success_url = reverse_lazy('dogs:list')

dogs/templates/dogs/base.html
<!-- Обязательное подключение статических тегов django-->
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'assets/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Питомник</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}" sizes="180x180">
<link rel="icon" href="{% static 'assets/img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
<link rel="icon" href="{% static 'assets/img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">
<link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
<link rel="mask-icon" href="{% static 'assets/img/favicons/safari-pinned-tab.svg' %}" color="#712cf9">
<link rel="icon" href="{% static 'assets/img/favicons/favicon.ico' %}">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    {% include 'dogs/includes/inc_menu.html' %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Приют собак в Ставрополе</h1>
      <p class="fs-5 text-body-secondary">
        В нашем приюте Вы можете взять собаку на выгул.
      </p>
    </div>
  </header>

  <main>


      {% block content_SingleObjectCard %}
        {# блок, который нужно будет расширять в шаблоне #}
      {% endblock %}



  </main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="{% static 'assets/brand/bootstrap-logo.svg' %}" alt="" width="24" height="19">
        <small class="d-block mb-3 text-body-secondary">&copy; 2017–2024</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </body>
</html>

dogs/templates/dogs/dogs_confirm_delete.html
{% extends 'dogs/base.html' %}
{% block content_SingleObjectCard %}
 <div class="row">
      <div class="col">
          <form method="post">
	        {% csrf_token %}
             <p>Действительно хотите удалить данную собаку:</p>
              <p> <b>{{object.last_name}} {{object.first_name}} {{object.patronymic}} </b> </p>
              <button type="submit" class="btn btn-success">Подтвердить</button>
              <a href="{% url 'dogs:list' %}" class="btn btn-success btn-warning">Отмена</a>
          </form>
      </div>
 </div>
{% endblock %}

dogs/templates/dogs/dogs_detail.html
{% extends 'dogs/base.html' %}
{% load path_tag_filter %}
{% block content_SingleObjectCard %}
<div class="row">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">

            <img class="card-img-top" width="600px" src="{% get_media_prefix object.photo %}" alt="Avatar"><br>
          <div class="card-header py-3 text-bg-primary border-primary">
            <h4 class="my-0 fw-normal">{{object.last_name}} {{object.first_name}}</h4>
          </div>

          <div class="card-body">
              <h1><small class="card-title text-body-secondary fw-light"> {{object.name}}</small></h1>

            Дата рождения: {{object.date_born | date:"d.m.Y"}}<br>
            Порода: {{object.breed}}<br>



             <a class="btn btn-primary" href="{% url 'dogs:list'  %}" role="button">К полному списку собак</a> <br/>


              <h2>О породе</h2>

              {{object.breed.description | safe}}<br>


</div>


          </div>
        </div>
      </div>

{% endblock %}

dogs/templates/dogs/dogs_form.html
{% extends 'dogs/base.html' %}
{% load crispy_forms_tags %}
{% block content_SingleObjectCard %}
<div class ="row text-start">
    <div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Добавление карточки собаки
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group mb-0">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.breed|as_crispy_field }}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.date_born|as_crispy_field }}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.photo|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                      {% if object %}
                                    <button type="submit" class="btn btn-success">Сохранить изменения</button>
                      {% else %}
                                    <button type="submit" class="btn btn-success">Создать новую карточку собаки</button>
                      {% endif %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Описание породы
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                     {{ form.as_p }}
                     {% if not foorloop.last %}
                      <hr/><hr/>
                     {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </form>
</div>
{% endblock %}

dogs/templates/dogs/dogs_list.html
{% extends 'dogs/base.html' %}
{% load path_tag_filter %}
{% block content_SingleObjectCard %}
<div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
  {% for object in object_list %}
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">

          <div class="card-header py-3 text-bg-primary border-primary">
            <h4 class="my-0 fw-normal">{{object.name}}</h4>
            <img width="400px" src="{% get_media_prefix object.photo %}" alt="Avatar"><br/><br/>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><small class="text-body-secondary fw-light"> </small></h1>

            Кличка: {{object.name}}<br>
            Дата рождения: {{object.date_born | date:"d.m.Y"}}<br>
            Порода: {{object.breed}}<br>



          </div>


            <div class="card-footer">
              <a class="btn btn-primary" href="{% url 'dogs:detail' object.pk %}" role="button">Подробнее ...</a>
              <a class="btn btn-primary" href="{% url 'dogs:update' object.pk %}" role="button">Изменить</a>
              <a class="btn btn-primary" href="{% url 'dogs:delete' object.pk %}" role="button">Удалить</a>
            </div>

        </div>
      </div>
  {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/home.html
<file html template/dogs/home.html>
<!doctype html>
<html>
<head>
<title>My Django test Page</title>
<meta name="description" content="Our first page">
<meta name="keywords" content="html template">
</head>
<body>
Hello, World!!!
</body>
</html>

dogs/templates/dogs/index.html
    <!doctype html>
    <html>
    <head>
    <title>HTML Page</title>
    <meta name="description" content="Our first page">
    <meta name="keywords" content="html tutorial template">
    </head>
    <body>
    Hello, Skypro!!!

<form method="post">
	{% csrf_token %}
	<input type="text" name="username" placeholder="name" />
    <br>
	<input type="email" name="email" placeholder="email@ia.eu" />
    <br>
    <textarea name="message"> </textarea>
    <br>
	<input type="submit" value="Отправить" />
</form>
    </body>
    </html>